# Generated by Django 5.0 on 2024-01-07 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 9, 35, 58, 954188, tzinfo=datetime.timezone.utc)),
        ),
    ]
